steps:
  # Step 1: Build the Docker image for the model service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlops-flask-app-440106/xgboost-flask-app', '.']

  # Step 2: Push the image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlops-flask-app-440106/xgboost-flask-app']

  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud run deploy xgboost-flask-app \
      --image gcr.io/mlops-flask-app-440106/xgboost-flask-app \
      --platform managed \
      --region us-central1 \
      --allow-unauthenticated
