name: Deploy to GCP

on:
  push:
    branches:
      - main  # Trigger on commits to the 'main' branch

jobs:
  build:
    name: Build and Deploy to GCP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Step 3: Build and push the Docker image to Google Container Registry (GCR)
      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/xgboost-flask-app .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/xgboost-flask-app

      # Step 4: Deploy the Docker image to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy xgboost-flask-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/xgboost-flask-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
