name: Build and Deploy to GCP

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/mlops-flask-app/xgboost-flask-app .
          docker push gcr.io/mlops-flask-app/xgboost-flask-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy xgboost-flask-app \
            --image gcr.io/mlops-flask-app/xgboost-flask-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
