name: MLOps Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code (updated to v3)
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment (updated to v4)
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests (replace with your actual test script)
    - name: Run tests
      run: |
        python tymestack.py  # Replace this with your actual test script

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    steps:
    # Step 5: Deploy the model (replace with actual deployment steps)
    - name: Deploy the model
      run: echo "Deploying model on server https://xgboost-flask-app-634631521378.us-central1.run.app"
